// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA4oyMDicSiq_QeGkLQ35TFSSKJ-ikvC3I',
    appId: '1:202448100371:web:e5dd7bad0793dd2c66f3e6',
    messagingSenderId: '202448100371',
    projectId: 'mobile-c52ca',
    authDomain: 'mobile-c52ca.firebaseapp.com',
    storageBucket: 'mobile-c52ca.firebasestorage.app',
    measurementId: 'G-51PJJKQ9WP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC3ZEjLALvGccrMsZM6AkqpU8KslDs5bic',
    appId: '1:202448100371:android:5fb1078f463fb44566f3e6',
    messagingSenderId: '202448100371',
    projectId: 'mobile-c52ca',
    storageBucket: 'mobile-c52ca.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCLgu37WC9h9OpUka7HPDSgC8Qx9SWv7LU',
    appId: '1:202448100371:ios:fa21f00b4d63962066f3e6',
    messagingSenderId: '202448100371',
    projectId: 'mobile-c52ca',
    storageBucket: 'mobile-c52ca.firebasestorage.app',
    androidClientId: '202448100371-4kqmbakao5938f4uk8ur1in3p0d80vdn.apps.googleusercontent.com',
    iosClientId: '202448100371-8682a79kn9r5nn5coukvdf00vic5fq8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCLgu37WC9h9OpUka7HPDSgC8Qx9SWv7LU',
    appId: '1:202448100371:ios:fa21f00b4d63962066f3e6',
    messagingSenderId: '202448100371',
    projectId: 'mobile-c52ca',
    storageBucket: 'mobile-c52ca.firebasestorage.app',
    androidClientId: '202448100371-4kqmbakao5938f4uk8ur1in3p0d80vdn.apps.googleusercontent.com',
    iosClientId: '202448100371-8682a79kn9r5nn5coukvdf00vic5fq8r.apps.googleusercontent.com',
    iosBundleId: 'com.example.mobile',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA4oyMDicSiq_QeGkLQ35TFSSKJ-ikvC3I',
    appId: '1:202448100371:web:98fa27a82474c71b66f3e6',
    messagingSenderId: '202448100371',
    projectId: 'mobile-c52ca',
    authDomain: 'mobile-c52ca.firebaseapp.com',
    storageBucket: 'mobile-c52ca.firebasestorage.app',
    measurementId: 'G-SPPCDEQ4E2',
  );
}
